# Generated by Django 5.1.6 on 2025-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_negative_marking',
            field=models.BooleanField(default=False, help_text='Whether negative marking was enabled for this quiz'),
        ),
    ]
