# Generated by Django 5.1.6 on 2025-04-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('quiz', '0002_quizattempt_is_negative_marking'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quiz_quizat_user_id_67c058_idx',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='subtopic',
            field=models.CharField(default='hi', help_text='Subtopic of the quiz', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='topic',
            field=models.CharField(default='hi', help_text='Topic of the quiz', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='attempted_options',
            field=models.JSONField(help_text='Options selected by the user'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='correct_attempts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='incorrect_attempts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='partial_attempts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='unattempted',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'created_at'], name='quiz_quizat_user_id_457f2b_idx'),
        ),
    ]
