# Generated by Django 5.2 on 2025-04-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quizattempt_quiz_quizat_user_id_67c058_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='subtopic',
            field=models.CharField(blank=True, help_text='Subtopic of the quiz', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='topic',
            field=models.CharField(blank=True, help_text='Topic of the quiz', max_length=255),
        ),
    ]
