# Generated by Django 5.1.6 on 2025-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonmistake',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='keytakeaway',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='needtolearn',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='relatedtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='resourcetabsuggestion',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='roadmaplevel',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='roadmaptopic',
            name='level',
        ),
        migrations.RemoveField(
            model_name='shortdescription',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='CommonMistake',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='KeyTakeaway',
        ),
        migrations.DeleteModel(
            name='NeedToLearn',
        ),
        migrations.DeleteModel(
            name='RelatedTopic',
        ),
        migrations.DeleteModel(
            name='ResourceTabSuggestion',
        ),
        migrations.DeleteModel(
            name='RoadMapLevel',
        ),
        migrations.DeleteModel(
            name='RoadMapTopic',
        ),
        migrations.DeleteModel(
            name='ShortDescription',
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
