# Generated by Django 5.1.6 on 2025-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_remove_commonmistake_subtopic_remove_faq_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('subtopic', models.CharField(blank=True, max_length=255)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true-false', 'True/False'), ('multiple-correct', 'Multiple Correct')], max_length=20)),
                ('question', models.TextField(unique=True)),
                ('options', models.JSONField()),
                ('correct_answers', models.JSONField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('gemini', 'Gemini'), ('manual', 'Manual')], default='gemini', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'subtopic', 'question_type'], name='search_app__topic_e39d4c_idx')],
            },
        ),
    ]
