# Generated by Django 5.1.6 on 2025-04-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('search_app', '0003_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('subtopic', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.FloatField()),
                ('correct_attempts', models.IntegerField()),
                ('incorrect_attempts', models.IntegerField()),
                ('partial_attempts', models.IntegerField()),
                ('unattempted', models.IntegerField()),
                ('total_time_taken', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='authentication.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.IntegerField()),
                ('attempted_options', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('is_partial', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='search_app.quizquestion')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='search_app.quizattempt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
