# Generated by Django 5.1.6 on 2025-04-16 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('search_app', '0005_remove_quizattempt_user_delete_questionattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_time_taken', models.IntegerField(help_text='Total time taken in seconds')),
                ('score', models.IntegerField(help_text='Total score achieved')),
                ('correct_attempts', models.IntegerField(help_text='Number of correctly attempted questions')),
                ('incorrect_attempts', models.IntegerField(help_text='Number of incorrectly attempted questions')),
                ('partial_attempts', models.IntegerField(help_text='Number of partially correct attempts')),
                ('unattempted', models.IntegerField(help_text='Number of unattempted questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.IntegerField(help_text='Time taken for this question in seconds')),
                ('attempted_options', models.JSONField(help_text='List of options selected by the user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.quizquestion')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='search_app.quizattempt')),
            ],
        ),
    ]
