# Generated by Django 5.1.6 on 2025-04-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0006_quizattempt_questionattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
