# Generated by Django 5.1.6 on 2025-04-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0007_remove_quizattempt_user_delete_questionattempt_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizquestion',
            new_name='search_app__topic_i_4051e9_idx',
            old_name='search_app__topic_e39d4c_idx',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='search_app.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='search_app__name_1abb79_idx'),
        ),
    ]
