# Generated by Django 5.1.6 on 2025-04-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_create_topics'),
        ('search_app', '0008_rename_search_app__topic_e39d4c_idx_search_app__topic_i_4051e9_idx_and_more'),
    ]

    operations = [
    ]
