# Generated by Django 5.1.6 on 2025-04-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0009_merge_20250420_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('read_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='search_app.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'subtopic'], name='search_app__topic_i_3049d6_idx')],
                'unique_together': {('topic', 'subtopic', 'url')},
            },
        ),
        migrations.CreateModel(
            name='DocumentationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('doc_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='search_app.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'subtopic'], name='search_app__topic_i_66771f_idx')],
                'unique_together': {('topic', 'subtopic', 'url')},
            },
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('duration', models.CharField(max_length=20)),
                ('thumbnail', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='search_app.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'subtopic'], name='search_app__topic_i_fb4160_idx')],
                'unique_together': {('topic', 'subtopic', 'url')},
            },
        ),
    ]
